site_name: GUILDA Doc
theme:
    name: material
    language: 'ja'
    logo: Figures/modularsmall.png
    favicon: Figures/modularsmall.png
    features:
        - navigation.tabs
        - content.code.annotate
    palette:
        scheme: default
        primary: light blue
        accent: light blue

nav:
    - Topページ:
        - "": index.md
        - 電力系統モデルについて: aboutPowerSystem/0TopPage.md
        - GUILDAの環境設定: SetEnvironment/0TopPage.md
        - リファレンス:
            - "": Reference/0TopPage.md
            - 電力系統モデルの定義:
                - "": Reference/defineNet/0TopPage.md
                - 新しい電力系統モデルの定義: Reference/defineNet/NewPowerNetwork.md
                - 新たな機器モデルの定義: Reference/defineNet/NewComponent.md
            - 制御器の付加:
                - "": Reference/addController/0TopPage.md
                - 新たな制御器モデルの実装: Reference/addController/NewController.md
            - シミュレ−ションの実行:
                - "": Reference/Analysis/net_simulate.md
                - コード例: Reference/Analysis/SampleCode.md
            - 近似線形化モデルの導出: Reference/Analysis/net_getsys.md
        - 一連の解析実行例: SeriesAnalysis/0TopPage.md
        - ソースコードの解説:
            - "": SourceCode/0TopPage.md
            - 電力系統クラス: SourceCode/power_network.md
            - 母線のクラス: SourceCode/bus.md
            - 機器のクラス: SourceCode/component.md
            - 制御器のクラス: SourceCode/controller.md
            - 送電網のクラス: SourceCode/branch.md
            - netのパラメータの読み方: SourceCode/NetProperties.md

extra:
    search:
        language: 'jp'
    font:
        text: "Note Sans JP"
        code: "Consolas"
extra_css:
    - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "https://unpkg.com/mermaid@8.0.0/dist/mermaid.css"
markdown_extensions:
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format
    - mdx_math:
        enable_dollar_delimiter: true
    - codehilite:
        linenums: true
        guess_lang: false
        use_pygments: false
        noclasses: true
    - footnotes:
    - admonition:
    - toc:
        permalink: true
        separator: '_'
    - attr_list:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tilde:
    - pymdownx.highlight:
    - pymdownx.inlinehilite
    - pymdownx.snippets
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML'
    - 'https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js'
copyright: 'Copyright © 2020- Tokyo Tech, Ishizaki Lab.'
